### ISSUE TITLE
[Enhancements] Plugin Views

### ISSUE THREAD

**Issue by starman2908** [realcopacetic/skin.copacetic#48] opened 2023-08-05 08:44 UTC
Hey sorry for the delay, but as we mentioned in the playback info thread, just starting this new one incase you decide to implement and track. I really want to thank you for implementing the new list/grid views for the menu lists in addons - TMDB Helper looks great, some other addons not so much.

I was thinking about all the different addon types and all the requests you must get for a variety of specific addons and wonder if there's a universal solution for them to make it simpler for your integration .... hopefully a lot of the code already exists in other parts of skin and would allowing the user to set some customisable options from the side menu of both view types for all different addons. 

I completely agree that any other views aside from the list/grid would be lost on most addons simply because there is no standard for the quality of artwork used by the authors. Some use high res, others don't. Some add text in their images, some don't. Some draw from so many  different image types/tags (poster/icon/thumbnail/fanart) which I imagine makes for so many headaches for skin developers like yourself. 

I wonder if the easiest way might be to include the options below for a solution for music, video and program add-ons:

_**Breadcrumbs (List/Grid View)**_ - an option to toggle on/off. Would save the duplication of information on list view and keep in line with the clean skin aesthetic. In grid view it would take care of the same issue for addons that have text in the icons.  

![1](https://github.com/realcopacetic/skin.copacetic/assets/36766279/543b1774-ba00-4d27-8dc5-fb9f35d0cc7e)
(Really love how you've implemented the icon artwork on the list view btw - very swish!! and great that it can be toggled between that or backgroud for addons that have low-res imagery). This leads to the next suggestion for the grid view:

_**Image display type (Grid)**_ - Would putting an option in the side menu letting the user select the type of image be a solution? Not dissimilar to the poster/fanart choice in video list containers, but just to include a toggle to select poster/icon/thumb/fanart in the lists.

![screenshot00006](https://github.com/realcopacetic/skin.copacetic/assets/36766279/07d8556c-72e0-4c5d-95de-e2e3d971435d)

I'm hoping this wouldn't be too much of headache to do.  I've seen a few requesting views/image type for a variety of specific addons when really it's more about how the addon creators have setup their images in the list containers. Least this way you could wash your hands of that and put the choice on the user as what they think looks best for them. 

Anyways food for thought. Keep up the great work!!

**Comment by realcopacetic** [comment] 2023-09-02 16:58
Hi sorry for the delay getting to this. Had a crazy few weeks with work/kids.

On the breadcrumb label, I've disabled it from showing up when it would be a duplicate of main label on List view, which should avoid the example you have above with 'Movies' showing twice. This will go live in 1.1.12, which I'll push to my repository in the next few days hopefully.

On Grid view, if the container content is set as, say, movies or tv shows, then it's treated the same as local library views. If there is no container content type set, then it should be locked to 'Breadcrumb' view, which is where there is no label on top of the focused icon and the label instead shows at the top. This is because I cannot control whether the icons in plugins will include text or not.

In terms of the view layouts, can you give me a bit more info about which layouts you are currently missing please

**Comment by realcopacetic** [comment] 2024-07-03 09:53
Option added to enable each view for addon/program windows in Settings >Copacetic > Views.

After speaking with some addon devs, it appears that some addons provide the functionality themselves to select from available viewtypes, see this thread for more: https://github.com/realcopacetic/skin.copacetic/issues/111. I believe this is where the plugin doesn't use addon/program windows, but instead uses Videos or Music in a non-standard way.

If the addons use standard content types for hteir plugins e.g. 'movies', 'tvshows' 'episodes' etc, then it should give you the same options you would have as if you were in your local library. Marking this as closed unless you come back with any more info about where things aren't working, thanks.

**Closed as completed by realcopacetic** 2024-07-03 09:53 UTC
Labels: enhancement
